name: Build Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_USER_TOKEN }}
      
      - name: Configure Git User
        run: |
          git config user.name atomic-redux-bot
          git config user.email atomic-redux-bot@email.com

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose --only tag:package

      - name: Test
        run: node common/scripts/install-run-rush.js test --verbose --only tag:package

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access_token: ${{ secrets.BOT_USER_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: false

      - name: Publish
        run: node common/scripts/install-run-rush.js publish --apply --target-branch master --publish --npm-auth-token ${{ secrets.NPM_TOKEN }} --add-commit-details

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.BOT_USER_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: true
      